// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventProtocols.proto

package com.example.project1;

public final class EventProtocols {
  private EventProtocols() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EventAddOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 partID = 1;
    /**
     * <code>required int64 partID = 1;</code>
     *
     * <pre>
     *Participant ID of person adding
     * </pre>
     */
    boolean hasPartID();
    /**
     * <code>required int64 partID = 1;</code>
     *
     * <pre>
     *Participant ID of person adding
     * </pre>
     */
    long getPartID();

    // required string char = 2;
    /**
     * <code>required string char = 2;</code>
     *
     * <pre>
     *The character added to the document
     * </pre>
     */
    boolean hasChar();
    /**
     * <code>required string char = 2;</code>
     *
     * <pre>
     *The character added to the document
     * </pre>
     */
    java.lang.String getChar();
    /**
     * <code>required string char = 2;</code>
     *
     * <pre>
     *The character added to the document
     * </pre>
     */
    com.google.protobuf.ByteString
        getCharBytes();
  }
  /**
   * Protobuf type {@code com.example.project1.EventAdd}
   *
   * <pre>
   *Message for someone adding a letter to text
   * </pre>
   */
  public static final class EventAdd extends
      com.google.protobuf.GeneratedMessage
      implements EventAddOrBuilder {
    // Use EventAdd.newBuilder() to construct.
    private EventAdd(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EventAdd(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EventAdd defaultInstance;
    public static EventAdd getDefaultInstance() {
      return defaultInstance;
    }

    public EventAdd getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EventAdd(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              partID_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              char_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.project1.EventProtocols.internal_static_com_example_project1_EventAdd_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.project1.EventProtocols.internal_static_com_example_project1_EventAdd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.project1.EventProtocols.EventAdd.class, com.example.project1.EventProtocols.EventAdd.Builder.class);
    }

    public static com.google.protobuf.Parser<EventAdd> PARSER =
        new com.google.protobuf.AbstractParser<EventAdd>() {
      public EventAdd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventAdd(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EventAdd> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 partID = 1;
    public static final int PARTID_FIELD_NUMBER = 1;
    private long partID_;
    /**
     * <code>required int64 partID = 1;</code>
     *
     * <pre>
     *Participant ID of person adding
     * </pre>
     */
    public boolean hasPartID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 partID = 1;</code>
     *
     * <pre>
     *Participant ID of person adding
     * </pre>
     */
    public long getPartID() {
      return partID_;
    }

    // required string char = 2;
    public static final int CHAR_FIELD_NUMBER = 2;
    private java.lang.Object char_;
    /**
     * <code>required string char = 2;</code>
     *
     * <pre>
     *The character added to the document
     * </pre>
     */
    public boolean hasChar() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string char = 2;</code>
     *
     * <pre>
     *The character added to the document
     * </pre>
     */
    public java.lang.String getChar() {
      java.lang.Object ref = char_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          char_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string char = 2;</code>
     *
     * <pre>
     *The character added to the document
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCharBytes() {
      java.lang.Object ref = char_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        char_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      partID_ = 0L;
      char_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPartID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChar()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, partID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCharBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, partID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCharBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.project1.EventProtocols.EventAdd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.project1.EventProtocols.EventAdd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.project1.EventProtocols.EventAdd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.project1.EventProtocols.EventAdd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.project1.EventProtocols.EventAdd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.project1.EventProtocols.EventAdd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.project1.EventProtocols.EventAdd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.project1.EventProtocols.EventAdd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.project1.EventProtocols.EventAdd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.project1.EventProtocols.EventAdd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.project1.EventProtocols.EventAdd prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.project1.EventAdd}
     *
     * <pre>
     *Message for someone adding a letter to text
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.project1.EventProtocols.EventAddOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.project1.EventProtocols.internal_static_com_example_project1_EventAdd_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.project1.EventProtocols.internal_static_com_example_project1_EventAdd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.project1.EventProtocols.EventAdd.class, com.example.project1.EventProtocols.EventAdd.Builder.class);
      }

      // Construct using com.example.project1.EventProtocols.EventAdd.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        partID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        char_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.project1.EventProtocols.internal_static_com_example_project1_EventAdd_descriptor;
      }

      public com.example.project1.EventProtocols.EventAdd getDefaultInstanceForType() {
        return com.example.project1.EventProtocols.EventAdd.getDefaultInstance();
      }

      public com.example.project1.EventProtocols.EventAdd build() {
        com.example.project1.EventProtocols.EventAdd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.project1.EventProtocols.EventAdd buildPartial() {
        com.example.project1.EventProtocols.EventAdd result = new com.example.project1.EventProtocols.EventAdd(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.partID_ = partID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.char_ = char_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.project1.EventProtocols.EventAdd) {
          return mergeFrom((com.example.project1.EventProtocols.EventAdd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.project1.EventProtocols.EventAdd other) {
        if (other == com.example.project1.EventProtocols.EventAdd.getDefaultInstance()) return this;
        if (other.hasPartID()) {
          setPartID(other.getPartID());
        }
        if (other.hasChar()) {
          bitField0_ |= 0x00000002;
          char_ = other.char_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPartID()) {
          
          return false;
        }
        if (!hasChar()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.project1.EventProtocols.EventAdd parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.project1.EventProtocols.EventAdd) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 partID = 1;
      private long partID_ ;
      /**
       * <code>required int64 partID = 1;</code>
       *
       * <pre>
       *Participant ID of person adding
       * </pre>
       */
      public boolean hasPartID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 partID = 1;</code>
       *
       * <pre>
       *Participant ID of person adding
       * </pre>
       */
      public long getPartID() {
        return partID_;
      }
      /**
       * <code>required int64 partID = 1;</code>
       *
       * <pre>
       *Participant ID of person adding
       * </pre>
       */
      public Builder setPartID(long value) {
        bitField0_ |= 0x00000001;
        partID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 partID = 1;</code>
       *
       * <pre>
       *Participant ID of person adding
       * </pre>
       */
      public Builder clearPartID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        partID_ = 0L;
        onChanged();
        return this;
      }

      // required string char = 2;
      private java.lang.Object char_ = "";
      /**
       * <code>required string char = 2;</code>
       *
       * <pre>
       *The character added to the document
       * </pre>
       */
      public boolean hasChar() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string char = 2;</code>
       *
       * <pre>
       *The character added to the document
       * </pre>
       */
      public java.lang.String getChar() {
        java.lang.Object ref = char_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          char_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string char = 2;</code>
       *
       * <pre>
       *The character added to the document
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCharBytes() {
        java.lang.Object ref = char_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          char_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string char = 2;</code>
       *
       * <pre>
       *The character added to the document
       * </pre>
       */
      public Builder setChar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        char_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string char = 2;</code>
       *
       * <pre>
       *The character added to the document
       * </pre>
       */
      public Builder clearChar() {
        bitField0_ = (bitField0_ & ~0x00000002);
        char_ = getDefaultInstance().getChar();
        onChanged();
        return this;
      }
      /**
       * <code>required string char = 2;</code>
       *
       * <pre>
       *The character added to the document
       * </pre>
       */
      public Builder setCharBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        char_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.project1.EventAdd)
    }

    static {
      defaultInstance = new EventAdd(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.example.project1.EventAdd)
  }

  public interface EventDelOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 partID = 1;
    /**
     * <code>required int64 partID = 1;</code>
     *
     * <pre>
     *Participant ID of person deleting
     * </pre>
     */
    boolean hasPartID();
    /**
     * <code>required int64 partID = 1;</code>
     *
     * <pre>
     *Participant ID of person deleting
     * </pre>
     */
    long getPartID();
  }
  /**
   * Protobuf type {@code com.example.project1.EventDel}
   *
   * <pre>
   *Message for someone deleting a letter in text
   * </pre>
   */
  public static final class EventDel extends
      com.google.protobuf.GeneratedMessage
      implements EventDelOrBuilder {
    // Use EventDel.newBuilder() to construct.
    private EventDel(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EventDel(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EventDel defaultInstance;
    public static EventDel getDefaultInstance() {
      return defaultInstance;
    }

    public EventDel getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EventDel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              partID_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.project1.EventProtocols.internal_static_com_example_project1_EventDel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.project1.EventProtocols.internal_static_com_example_project1_EventDel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.project1.EventProtocols.EventDel.class, com.example.project1.EventProtocols.EventDel.Builder.class);
    }

    public static com.google.protobuf.Parser<EventDel> PARSER =
        new com.google.protobuf.AbstractParser<EventDel>() {
      public EventDel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventDel(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EventDel> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 partID = 1;
    public static final int PARTID_FIELD_NUMBER = 1;
    private long partID_;
    /**
     * <code>required int64 partID = 1;</code>
     *
     * <pre>
     *Participant ID of person deleting
     * </pre>
     */
    public boolean hasPartID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 partID = 1;</code>
     *
     * <pre>
     *Participant ID of person deleting
     * </pre>
     */
    public long getPartID() {
      return partID_;
    }

    private void initFields() {
      partID_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPartID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, partID_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, partID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.project1.EventProtocols.EventDel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.project1.EventProtocols.EventDel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.project1.EventProtocols.EventDel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.project1.EventProtocols.EventDel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.project1.EventProtocols.EventDel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.project1.EventProtocols.EventDel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.project1.EventProtocols.EventDel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.project1.EventProtocols.EventDel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.project1.EventProtocols.EventDel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.project1.EventProtocols.EventDel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.project1.EventProtocols.EventDel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.project1.EventDel}
     *
     * <pre>
     *Message for someone deleting a letter in text
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.project1.EventProtocols.EventDelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.project1.EventProtocols.internal_static_com_example_project1_EventDel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.project1.EventProtocols.internal_static_com_example_project1_EventDel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.project1.EventProtocols.EventDel.class, com.example.project1.EventProtocols.EventDel.Builder.class);
      }

      // Construct using com.example.project1.EventProtocols.EventDel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        partID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.project1.EventProtocols.internal_static_com_example_project1_EventDel_descriptor;
      }

      public com.example.project1.EventProtocols.EventDel getDefaultInstanceForType() {
        return com.example.project1.EventProtocols.EventDel.getDefaultInstance();
      }

      public com.example.project1.EventProtocols.EventDel build() {
        com.example.project1.EventProtocols.EventDel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.project1.EventProtocols.EventDel buildPartial() {
        com.example.project1.EventProtocols.EventDel result = new com.example.project1.EventProtocols.EventDel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.partID_ = partID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.project1.EventProtocols.EventDel) {
          return mergeFrom((com.example.project1.EventProtocols.EventDel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.project1.EventProtocols.EventDel other) {
        if (other == com.example.project1.EventProtocols.EventDel.getDefaultInstance()) return this;
        if (other.hasPartID()) {
          setPartID(other.getPartID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPartID()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.project1.EventProtocols.EventDel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.project1.EventProtocols.EventDel) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 partID = 1;
      private long partID_ ;
      /**
       * <code>required int64 partID = 1;</code>
       *
       * <pre>
       *Participant ID of person deleting
       * </pre>
       */
      public boolean hasPartID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 partID = 1;</code>
       *
       * <pre>
       *Participant ID of person deleting
       * </pre>
       */
      public long getPartID() {
        return partID_;
      }
      /**
       * <code>required int64 partID = 1;</code>
       *
       * <pre>
       *Participant ID of person deleting
       * </pre>
       */
      public Builder setPartID(long value) {
        bitField0_ |= 0x00000001;
        partID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 partID = 1;</code>
       *
       * <pre>
       *Participant ID of person deleting
       * </pre>
       */
      public Builder clearPartID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        partID_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.project1.EventDel)
    }

    static {
      defaultInstance = new EventDel(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.example.project1.EventDel)
  }

  public interface EventMoveOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 partID = 1;
    /**
     * <code>required int64 partID = 1;</code>
     *
     * <pre>
     *Participant ID of person moving cursor
     * </pre>
     */
    boolean hasPartID();
    /**
     * <code>required int64 partID = 1;</code>
     *
     * <pre>
     *Participant ID of person moving cursor
     * </pre>
     */
    long getPartID();

    // required int64 newLoc = 2;
    /**
     * <code>required int64 newLoc = 2;</code>
     *
     * <pre>
     *Location of cursor
     * </pre>
     */
    boolean hasNewLoc();
    /**
     * <code>required int64 newLoc = 2;</code>
     *
     * <pre>
     *Location of cursor
     * </pre>
     */
    long getNewLoc();
  }
  /**
   * Protobuf type {@code com.example.project1.EventMove}
   *
   * <pre>
   *Message for someone moving cursor
   * </pre>
   */
  public static final class EventMove extends
      com.google.protobuf.GeneratedMessage
      implements EventMoveOrBuilder {
    // Use EventMove.newBuilder() to construct.
    private EventMove(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EventMove(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EventMove defaultInstance;
    public static EventMove getDefaultInstance() {
      return defaultInstance;
    }

    public EventMove getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EventMove(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              partID_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              newLoc_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.project1.EventProtocols.internal_static_com_example_project1_EventMove_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.project1.EventProtocols.internal_static_com_example_project1_EventMove_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.project1.EventProtocols.EventMove.class, com.example.project1.EventProtocols.EventMove.Builder.class);
    }

    public static com.google.protobuf.Parser<EventMove> PARSER =
        new com.google.protobuf.AbstractParser<EventMove>() {
      public EventMove parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventMove(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EventMove> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 partID = 1;
    public static final int PARTID_FIELD_NUMBER = 1;
    private long partID_;
    /**
     * <code>required int64 partID = 1;</code>
     *
     * <pre>
     *Participant ID of person moving cursor
     * </pre>
     */
    public boolean hasPartID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 partID = 1;</code>
     *
     * <pre>
     *Participant ID of person moving cursor
     * </pre>
     */
    public long getPartID() {
      return partID_;
    }

    // required int64 newLoc = 2;
    public static final int NEWLOC_FIELD_NUMBER = 2;
    private long newLoc_;
    /**
     * <code>required int64 newLoc = 2;</code>
     *
     * <pre>
     *Location of cursor
     * </pre>
     */
    public boolean hasNewLoc() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 newLoc = 2;</code>
     *
     * <pre>
     *Location of cursor
     * </pre>
     */
    public long getNewLoc() {
      return newLoc_;
    }

    private void initFields() {
      partID_ = 0L;
      newLoc_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPartID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNewLoc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, partID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, newLoc_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, partID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, newLoc_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.project1.EventProtocols.EventMove parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.project1.EventProtocols.EventMove parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.project1.EventProtocols.EventMove parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.project1.EventProtocols.EventMove parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.project1.EventProtocols.EventMove parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.project1.EventProtocols.EventMove parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.project1.EventProtocols.EventMove parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.project1.EventProtocols.EventMove parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.project1.EventProtocols.EventMove parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.project1.EventProtocols.EventMove parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.project1.EventProtocols.EventMove prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.project1.EventMove}
     *
     * <pre>
     *Message for someone moving cursor
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.project1.EventProtocols.EventMoveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.project1.EventProtocols.internal_static_com_example_project1_EventMove_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.project1.EventProtocols.internal_static_com_example_project1_EventMove_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.project1.EventProtocols.EventMove.class, com.example.project1.EventProtocols.EventMove.Builder.class);
      }

      // Construct using com.example.project1.EventProtocols.EventMove.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        partID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        newLoc_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.project1.EventProtocols.internal_static_com_example_project1_EventMove_descriptor;
      }

      public com.example.project1.EventProtocols.EventMove getDefaultInstanceForType() {
        return com.example.project1.EventProtocols.EventMove.getDefaultInstance();
      }

      public com.example.project1.EventProtocols.EventMove build() {
        com.example.project1.EventProtocols.EventMove result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.project1.EventProtocols.EventMove buildPartial() {
        com.example.project1.EventProtocols.EventMove result = new com.example.project1.EventProtocols.EventMove(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.partID_ = partID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.newLoc_ = newLoc_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.project1.EventProtocols.EventMove) {
          return mergeFrom((com.example.project1.EventProtocols.EventMove)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.project1.EventProtocols.EventMove other) {
        if (other == com.example.project1.EventProtocols.EventMove.getDefaultInstance()) return this;
        if (other.hasPartID()) {
          setPartID(other.getPartID());
        }
        if (other.hasNewLoc()) {
          setNewLoc(other.getNewLoc());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPartID()) {
          
          return false;
        }
        if (!hasNewLoc()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.project1.EventProtocols.EventMove parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.project1.EventProtocols.EventMove) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 partID = 1;
      private long partID_ ;
      /**
       * <code>required int64 partID = 1;</code>
       *
       * <pre>
       *Participant ID of person moving cursor
       * </pre>
       */
      public boolean hasPartID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 partID = 1;</code>
       *
       * <pre>
       *Participant ID of person moving cursor
       * </pre>
       */
      public long getPartID() {
        return partID_;
      }
      /**
       * <code>required int64 partID = 1;</code>
       *
       * <pre>
       *Participant ID of person moving cursor
       * </pre>
       */
      public Builder setPartID(long value) {
        bitField0_ |= 0x00000001;
        partID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 partID = 1;</code>
       *
       * <pre>
       *Participant ID of person moving cursor
       * </pre>
       */
      public Builder clearPartID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        partID_ = 0L;
        onChanged();
        return this;
      }

      // required int64 newLoc = 2;
      private long newLoc_ ;
      /**
       * <code>required int64 newLoc = 2;</code>
       *
       * <pre>
       *Location of cursor
       * </pre>
       */
      public boolean hasNewLoc() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 newLoc = 2;</code>
       *
       * <pre>
       *Location of cursor
       * </pre>
       */
      public long getNewLoc() {
        return newLoc_;
      }
      /**
       * <code>required int64 newLoc = 2;</code>
       *
       * <pre>
       *Location of cursor
       * </pre>
       */
      public Builder setNewLoc(long value) {
        bitField0_ |= 0x00000002;
        newLoc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 newLoc = 2;</code>
       *
       * <pre>
       *Location of cursor
       * </pre>
       */
      public Builder clearNewLoc() {
        bitField0_ = (bitField0_ & ~0x00000002);
        newLoc_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.project1.EventMove)
    }

    static {
      defaultInstance = new EventMove(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.example.project1.EventMove)
  }

  public interface EventJoinOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 partID = 1;
    /**
     * <code>required int64 partID = 1;</code>
     *
     * <pre>
     *Participant ID of person who just joined (To initialize cursor loc)
     * </pre>
     */
    boolean hasPartID();
    /**
     * <code>required int64 partID = 1;</code>
     *
     * <pre>
     *Participant ID of person who just joined (To initialize cursor loc)
     * </pre>
     */
    long getPartID();
  }
  /**
   * Protobuf type {@code com.example.project1.EventJoin}
   *
   * <pre>
   *Message for someone who just joined document (after they have caught up on events)
   * </pre>
   */
  public static final class EventJoin extends
      com.google.protobuf.GeneratedMessage
      implements EventJoinOrBuilder {
    // Use EventJoin.newBuilder() to construct.
    private EventJoin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EventJoin(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EventJoin defaultInstance;
    public static EventJoin getDefaultInstance() {
      return defaultInstance;
    }

    public EventJoin getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EventJoin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              partID_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.project1.EventProtocols.internal_static_com_example_project1_EventJoin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.project1.EventProtocols.internal_static_com_example_project1_EventJoin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.project1.EventProtocols.EventJoin.class, com.example.project1.EventProtocols.EventJoin.Builder.class);
    }

    public static com.google.protobuf.Parser<EventJoin> PARSER =
        new com.google.protobuf.AbstractParser<EventJoin>() {
      public EventJoin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventJoin(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EventJoin> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 partID = 1;
    public static final int PARTID_FIELD_NUMBER = 1;
    private long partID_;
    /**
     * <code>required int64 partID = 1;</code>
     *
     * <pre>
     *Participant ID of person who just joined (To initialize cursor loc)
     * </pre>
     */
    public boolean hasPartID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 partID = 1;</code>
     *
     * <pre>
     *Participant ID of person who just joined (To initialize cursor loc)
     * </pre>
     */
    public long getPartID() {
      return partID_;
    }

    private void initFields() {
      partID_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPartID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, partID_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, partID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.project1.EventProtocols.EventJoin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.project1.EventProtocols.EventJoin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.project1.EventProtocols.EventJoin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.project1.EventProtocols.EventJoin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.project1.EventProtocols.EventJoin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.project1.EventProtocols.EventJoin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.project1.EventProtocols.EventJoin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.project1.EventProtocols.EventJoin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.project1.EventProtocols.EventJoin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.project1.EventProtocols.EventJoin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.project1.EventProtocols.EventJoin prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.project1.EventJoin}
     *
     * <pre>
     *Message for someone who just joined document (after they have caught up on events)
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.project1.EventProtocols.EventJoinOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.project1.EventProtocols.internal_static_com_example_project1_EventJoin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.project1.EventProtocols.internal_static_com_example_project1_EventJoin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.project1.EventProtocols.EventJoin.class, com.example.project1.EventProtocols.EventJoin.Builder.class);
      }

      // Construct using com.example.project1.EventProtocols.EventJoin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        partID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.project1.EventProtocols.internal_static_com_example_project1_EventJoin_descriptor;
      }

      public com.example.project1.EventProtocols.EventJoin getDefaultInstanceForType() {
        return com.example.project1.EventProtocols.EventJoin.getDefaultInstance();
      }

      public com.example.project1.EventProtocols.EventJoin build() {
        com.example.project1.EventProtocols.EventJoin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.project1.EventProtocols.EventJoin buildPartial() {
        com.example.project1.EventProtocols.EventJoin result = new com.example.project1.EventProtocols.EventJoin(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.partID_ = partID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.project1.EventProtocols.EventJoin) {
          return mergeFrom((com.example.project1.EventProtocols.EventJoin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.project1.EventProtocols.EventJoin other) {
        if (other == com.example.project1.EventProtocols.EventJoin.getDefaultInstance()) return this;
        if (other.hasPartID()) {
          setPartID(other.getPartID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPartID()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.project1.EventProtocols.EventJoin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.project1.EventProtocols.EventJoin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 partID = 1;
      private long partID_ ;
      /**
       * <code>required int64 partID = 1;</code>
       *
       * <pre>
       *Participant ID of person who just joined (To initialize cursor loc)
       * </pre>
       */
      public boolean hasPartID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 partID = 1;</code>
       *
       * <pre>
       *Participant ID of person who just joined (To initialize cursor loc)
       * </pre>
       */
      public long getPartID() {
        return partID_;
      }
      /**
       * <code>required int64 partID = 1;</code>
       *
       * <pre>
       *Participant ID of person who just joined (To initialize cursor loc)
       * </pre>
       */
      public Builder setPartID(long value) {
        bitField0_ |= 0x00000001;
        partID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 partID = 1;</code>
       *
       * <pre>
       *Participant ID of person who just joined (To initialize cursor loc)
       * </pre>
       */
      public Builder clearPartID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        partID_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.project1.EventJoin)
    }

    static {
      defaultInstance = new EventJoin(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.example.project1.EventJoin)
  }

  public interface EventLeaveOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 partID = 1;
    /**
     * <code>required int64 partID = 1;</code>
     *
     * <pre>
     *Participant ID of person who just left (To remove from list)
     * </pre>
     */
    boolean hasPartID();
    /**
     * <code>required int64 partID = 1;</code>
     *
     * <pre>
     *Participant ID of person who just left (To remove from list)
     * </pre>
     */
    long getPartID();
  }
  /**
   * Protobuf type {@code com.example.project1.EventLeave}
   *
   * <pre>
   *Message for someone who just disconnected from document
   * </pre>
   */
  public static final class EventLeave extends
      com.google.protobuf.GeneratedMessage
      implements EventLeaveOrBuilder {
    // Use EventLeave.newBuilder() to construct.
    private EventLeave(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EventLeave(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EventLeave defaultInstance;
    public static EventLeave getDefaultInstance() {
      return defaultInstance;
    }

    public EventLeave getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EventLeave(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              partID_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.project1.EventProtocols.internal_static_com_example_project1_EventLeave_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.project1.EventProtocols.internal_static_com_example_project1_EventLeave_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.project1.EventProtocols.EventLeave.class, com.example.project1.EventProtocols.EventLeave.Builder.class);
    }

    public static com.google.protobuf.Parser<EventLeave> PARSER =
        new com.google.protobuf.AbstractParser<EventLeave>() {
      public EventLeave parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventLeave(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EventLeave> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 partID = 1;
    public static final int PARTID_FIELD_NUMBER = 1;
    private long partID_;
    /**
     * <code>required int64 partID = 1;</code>
     *
     * <pre>
     *Participant ID of person who just left (To remove from list)
     * </pre>
     */
    public boolean hasPartID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 partID = 1;</code>
     *
     * <pre>
     *Participant ID of person who just left (To remove from list)
     * </pre>
     */
    public long getPartID() {
      return partID_;
    }

    private void initFields() {
      partID_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPartID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, partID_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, partID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.project1.EventProtocols.EventLeave parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.project1.EventProtocols.EventLeave parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.project1.EventProtocols.EventLeave parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.project1.EventProtocols.EventLeave parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.project1.EventProtocols.EventLeave parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.project1.EventProtocols.EventLeave parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.project1.EventProtocols.EventLeave parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.project1.EventProtocols.EventLeave parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.project1.EventProtocols.EventLeave parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.project1.EventProtocols.EventLeave parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.project1.EventProtocols.EventLeave prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.project1.EventLeave}
     *
     * <pre>
     *Message for someone who just disconnected from document
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.project1.EventProtocols.EventLeaveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.project1.EventProtocols.internal_static_com_example_project1_EventLeave_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.project1.EventProtocols.internal_static_com_example_project1_EventLeave_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.project1.EventProtocols.EventLeave.class, com.example.project1.EventProtocols.EventLeave.Builder.class);
      }

      // Construct using com.example.project1.EventProtocols.EventLeave.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        partID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.project1.EventProtocols.internal_static_com_example_project1_EventLeave_descriptor;
      }

      public com.example.project1.EventProtocols.EventLeave getDefaultInstanceForType() {
        return com.example.project1.EventProtocols.EventLeave.getDefaultInstance();
      }

      public com.example.project1.EventProtocols.EventLeave build() {
        com.example.project1.EventProtocols.EventLeave result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.project1.EventProtocols.EventLeave buildPartial() {
        com.example.project1.EventProtocols.EventLeave result = new com.example.project1.EventProtocols.EventLeave(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.partID_ = partID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.project1.EventProtocols.EventLeave) {
          return mergeFrom((com.example.project1.EventProtocols.EventLeave)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.project1.EventProtocols.EventLeave other) {
        if (other == com.example.project1.EventProtocols.EventLeave.getDefaultInstance()) return this;
        if (other.hasPartID()) {
          setPartID(other.getPartID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPartID()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.project1.EventProtocols.EventLeave parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.project1.EventProtocols.EventLeave) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 partID = 1;
      private long partID_ ;
      /**
       * <code>required int64 partID = 1;</code>
       *
       * <pre>
       *Participant ID of person who just left (To remove from list)
       * </pre>
       */
      public boolean hasPartID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 partID = 1;</code>
       *
       * <pre>
       *Participant ID of person who just left (To remove from list)
       * </pre>
       */
      public long getPartID() {
        return partID_;
      }
      /**
       * <code>required int64 partID = 1;</code>
       *
       * <pre>
       *Participant ID of person who just left (To remove from list)
       * </pre>
       */
      public Builder setPartID(long value) {
        bitField0_ |= 0x00000001;
        partID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 partID = 1;</code>
       *
       * <pre>
       *Participant ID of person who just left (To remove from list)
       * </pre>
       */
      public Builder clearPartID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        partID_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.project1.EventLeave)
    }

    static {
      defaultInstance = new EventLeave(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.example.project1.EventLeave)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_project1_EventAdd_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_project1_EventAdd_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_project1_EventDel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_project1_EventDel_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_project1_EventMove_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_project1_EventMove_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_project1_EventJoin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_project1_EventJoin_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_project1_EventLeave_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_project1_EventLeave_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024EventProtocols.proto\022\024com.example.proj" +
      "ect1\"(\n\010EventAdd\022\016\n\006partID\030\001 \002(\003\022\014\n\004char" +
      "\030\002 \002(\t\"\032\n\010EventDel\022\016\n\006partID\030\001 \002(\003\"+\n\tEv" +
      "entMove\022\016\n\006partID\030\001 \002(\003\022\016\n\006newLoc\030\002 \002(\003\"" +
      "\033\n\tEventJoin\022\016\n\006partID\030\001 \002(\003\"\034\n\nEventLea" +
      "ve\022\016\n\006partID\030\001 \002(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_example_project1_EventAdd_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_example_project1_EventAdd_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_example_project1_EventAdd_descriptor,
              new java.lang.String[] { "PartID", "Char", });
          internal_static_com_example_project1_EventDel_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_example_project1_EventDel_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_example_project1_EventDel_descriptor,
              new java.lang.String[] { "PartID", });
          internal_static_com_example_project1_EventMove_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_example_project1_EventMove_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_example_project1_EventMove_descriptor,
              new java.lang.String[] { "PartID", "NewLoc", });
          internal_static_com_example_project1_EventJoin_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_example_project1_EventJoin_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_example_project1_EventJoin_descriptor,
              new java.lang.String[] { "PartID", });
          internal_static_com_example_project1_EventLeave_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_example_project1_EventLeave_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_example_project1_EventLeave_descriptor,
              new java.lang.String[] { "PartID", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
